name: BWildTP
main: org.betamc.bwildtp.JWildTP
version: 1.0.2
author: JohnyMuffin, SvGaming
description: A plugin to randomly teleport, fork of JWildTP
commands:
  wild:
    description: A command to randomly teleport, fork of JWildTP
    usage: /<command>
    aliases: [random, rtp, randomtp]
permissions:
  bwildtp.wild:
    description: Allows a player to randomly teleport
  bwildtp.wild.cooldown.exempt:
    description: Allows a player to be exempt from the Wild TP cooldown
  jwildtp.wild:
    description: Allows a player to randomly teleport (left for compatibility reasons)